### ISSUE TITLE
New actions

### ISSUE THREAD

**Issue by bryanvam** [jeffmikels/ProPresenter-API#1]
Found a new action called stageDisplaySetIndex that gets called when changing stage displays

**Comment by bryanvam** [comment]
Found a new action called clockStartStop that gets called when starting or stopping a clock

**Comment by bryanvam** [comment]
Found a new action called messageSend that gets called when showing a message
Found a new action called messageHide that gets called when hiding a message

**Comment by bryanvam** [comment]
Found a new request called clockRequest that will return a list of clocks
Found a new request called messageRequest that will return a list of messages

**Comment by jeffmikels** [comment]
These are helpful. Thanks.

**Comment by jeffmikels** [comment]
> Found a new request called clockRequest that will return a list of clocks
> Found a new request called messageRequest that will return a list of messages

Would you be willing to add your findings to the main README.md file? or send me your examples so I can paste them into the Readme?

**Comment by bryanvam** [comment]
Yes sure,  I will do a PR



________________________________

**Comment by emersonian** [comment]
@bryanvam Can you paste the exact JSON for your newfound actions? specifically clockRequest. Thanks.
