### ISSUE TITLE
websocket connection for stagedisplay

### ISSUE THREAD

**Issue by adminJunoit** [jeffmikels/ProPresenter-API#14]
Hi there, 

Thank you for this wonderful documentation. We've been using websocket to send stagedisplay to OBS and it's been working wonderfully. We've recently upgraded to Propresenter 7.8 and for some reason, the /stagedisplay endpoint cannot be reached, has anyone experience anything similar? do they change the endpoint for stagedisplay?

Thanks

**Comment by greyshirtguy** [comment]
I have not noticed! I'm already running 7.8.3 beta so it's been a while since I ran 7.8.0
Which exact version or Pro7 and Operatiing system?

**Comment by greyshirtguy** [comment]
Also, there is a bug/issue that I have seen where Pro7 stops listening altogether!
A tell-tale sign of that is the network preferences showing nothing for IP Address:
Maybe check what your network preferences screen looks like - is an IP address listed/shown?
![image](https://user-images.githubusercontent.com/1886513/155667179-d2bde885-e129-42bd-9d34-26b3d7315303.png)

**Comment by adminJunoit** [comment]
Hi there,

Yes, exactly this, I think this was what happened, thank you for sharing the solution, I'll check the solutions and close this issue ticket.

Cheers
