### ISSUE TITLE
tmr response for display

### ISSUE THREAD

**Issue by bryanvam** [jeffmikels/ProPresenter-API#2]
{"acn":"tmr","uid":"F3F5B945-D0B7-45DB-99FE-B2DB6F846615","txt":"10:08:12"}

How can I know for which clock this should be for?

**Comment by jeffmikels** [comment]
I haven't played with the clocks before, but I think the uid should be persistent between app restarts, so once you determine which clock is which by the uid, it should stay the same in the future.
