### ISSUE TITLE
Enable Copyright display

### ISSUE THREAD

**Issue by rchadgray** [jeffmikels/ProPresenter-API#5]
Has anyone see the text that PP automatically puts on slides when you enable the Copyright Display?

It would be nice to grab this Copyright text and display it like we do the lyrics in OBS.

Thanks,
Chad

**Comment by jeffmikels** [comment]
Is there any update on this? Does copyright data get exposed to the apps through the API?

**Comment by greyshirtguy** [comment]
In all my exploration, I'm pretty sure it is _not_ exposed anywhere in the remote API.
I suspect it's not in Stage-Display API either.
