### ISSUE TITLE
Actions for creating slides or updating text?

### ISSUE THREAD

**Issue by winternet-studio** [jeffmikels/ProPresenter-API#6]
I don't see any actions for creating new slides or modifying text on existing slides - is that not possible?

I want to have some "dynamic text" on a slide which I can change through the API so I can push updates externally into ProPresenter. Or could there be some other way to scripting that...

**Comment by cgarwood** [comment]
Not possible in ProPresenter 6. There's been some changes to the API for ProPresenter 7 but I don't think its been fully documented yet.

Depending on how you need to use it, you might be able to get away with using Messages since they can be updated through the API?

**Comment by rchadgray** [comment]
I would think of this API as this.  If ProPresenter's external apps (stage display and remote) can do something that means the API can do that.  I do not think any of these apps can create or edit content.

**Comment by winternet-studio** [comment]
That's unfortunate... I guess the workaround for now will be to either use a webpage that updates occasionally or a whole different system which creates an NDI stream that PP uses...

Since the API actions are not officially documented how do you discover the actions though? Are you looking at network traffic when using the remotes?

**Comment by rchadgray** [comment]
Packet sniffing while using apps is how i have done it in the past.  :)

**Comment by jeffmikels** [comment]
> I don't see any actions for creating new slides or modifying text on existing slides - is that not possible?
> 
> I want to have some "dynamic text" on a slide which I can change through the API so I can push updates externally into ProPresenter. Or could there be some other way to scripting that...

Closing this issue... currently, the best workaround is to use OBS or another titling software. Here are some steps:

- Install OBS with the Virtual Camera extension or an NDI extension.
- Create a video input in ProPresenter and add that to a slide
- Use the OBS Websocket interface to dynamically update title text in OBS

This could all become moot if someone figures out how to edit Pro 7 Props through the API.
